Eromonsalem/Eromonsalem/urls.py
from django.contrib import admin
from django.urls import path,include
from Eron_app import views

urlpatterns = [
    path('', views.index ,name='index'),
    path('thanks/',views.thankyou,name='thankyou'),
    path('Eron_app/',include('Eron_app.urls')),
    path('admin/', admin.site.urls),
]

Eromonsalem/Eron_app/urls.py
from django.urls import path
from Eron_app import views

app_name= 'Eron_app'



urlpatterns = [
    path('about/',views.about, name='about'),
    path('blog/',views.blog, name='blog'),
    path('contact/',views.contact, name='contact'),
    path('FQA/',views.FQa, name='FQA'),
    path('policy/',views.Policy, name='policy'),
    path('privacy/', views.Privacy, name='privacy'),
    path('service/', views.Service, name='service'),
    path('servicedeal/',views.Servicedeal, name='servicedeal'),
]

Eromonsalem/Eron_app/models.py
from django.db import models

# Create your models here.


class ServiceModel(models.Model):
    SERVICE_CHOICES = [
    ('Web design','WEB DESIGN'),
    ('Project management', 'PROJECT MANAGEMENT'),
    ('It training','IT TRAINING'),
    ('Remote support','REMOTE SUPPORT'),
    ('Cloud computing','CLOUD COMPUTING'),
    ('Programming and development','PROGRAMMING AND DEVELOPMENT'),]


    Fullname=models.CharField(max_length=264 ,unique=True)
    Email=models.EmailField(max_length=265, unique=True)
    service=models.CharField(max_length=50, choices=SERVICE_CHOICES ,default='Web design')





class contactModel(models.Model):
    fullname=models.CharField(max_length=264,unique=True)
    email=models.EmailField(max_length=265,unique=True)
    message=models.CharField(max_length=500)

Eromonsalem/Eron_app/forms.py
from django.forms import ModelForm,Textarea
from Eron_app.models import contactModel,ServiceModel

class contactForm(ModelForm):
    class Meta():
        model=contactModel
        fields=("fullname" ,"email" ,"message")
        widgets={
            'message':Textarea(attrs={'cols':35,'rows':5}),
        }


class ServiceForm(ModelForm):
    class Meta():
        model=ServiceModel
        fields='__all__'

Eromonsalem/Eron_app/views.py
from django.shortcuts import render
from Eron_app.forms import contactForm,ServiceForm

# Create your views here.

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request,'about.html')

def blog(request):
    return render(request,'blog.html')

def contact(request):

    form=contactForm()

    if request.method=='POST':
        form= contactForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return thankyou(request)
        else:
            print('ERROR FORM INVALID ')    
   
    return render(request,'contact.html',{'form':form})




def FQa(request):
    return render(request ,'FQA.html')

def Policy(request):
    return render(request ,'Policy.html')

def Privacy(request):
    return render(request, 'Privacy.html')

def Service(request):

    formm=ServiceForm()

    if request.method=='POST':
        formm= ServiceForm(request.POST)

        if formm.is_valid():
            formm.save(commit=True)
            return thankyou(request)
        else:
            print('INVALID SELECTION ')    
   

    return render(request ,'Service.html',{'formm':formm})



def Servicedeal(request):
    return render(request, 'Servicedeal.html')

def thankyou(request):
    return render(request,'thanks.html')

Eromonsalem/templates/Base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "CSS/style.css"  %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
     <!-- Icon Font Stylesheet -->
     <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
 
    
  </head>
  <body>

    <!-- Topbar Start -->
    <div class="container-fluid ps-5 pe-0 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-md-6  text-lg-start mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center">
                    <a class="text-body py-2 pe-3 border-end" href="{% url 'Eron_app:FQA' %}"><small>FAQs</small></a>
                    <a class="text-body py-2 px-3 border-end" href="{% url 'Eron_app:servicedeal' %}"><small>Service Level Agreement</small></a>
                    <a class="text-body py-2 px-3 border-end" href="{% url 'Eron_app:privacy' %}"><small>Privacy</small></a>
                    <a class="text-body py-2 px-3 border-end" href="{% url 'Eron_app:policy' %}"><small>Policy</small></a>
                </div>
            </div>
            <div class="col-md-6  text-lg-end">
                <div class="position-relative d-inline-flex align-items-center bg-primary text-white top-shape px-5">
                    <div class="me-3 pe-3 border-end py-2">
                        <p class="m-0"><i class="fa fa-envelope-open me-2"></i>Eromonsalemconsulting@gmail.com</p>
                    </div>
                    <div class="py-2">
                        <p class="m-0"><i class="fa fa-phone-alt me-2"></i>+1 647-562-8447</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <section id="nav-bar">
         <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static "images/Eronsalemmm.png" %}" alt="Logo" ></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                  <a class="nav-link "  href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'Eron_app:about' %}">About</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle " href="{% url 'Eron_app:service' %}"  aria-expanded="false">
                    Services
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'Eron_app:service' %}">Get quotes -Services and<br> more</a></li>
                    <li><a class="dropdown-item" href="{% url 'Eron_app:contact' %}">Contact Us- Contact Us <br>For more info</a></li>
                  </ul>
                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'Eron_app:blog' %}">Blog</a>
                  </li>
                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'Eron_app:contact' %}">Contact Us</a>
                  </li>
                </li>
              </ul>
            </div>
          </div>
        </nav>
    </section>
    <div>
     {% block body_block %}

     {% endblock %}

    </div>
    

    <!-- Footer Start -->
    <!-- Begin Mailchimp Signup Form -->
    <style type="text/css">
        #mc_embed_signup{ font:20px ,Arial,sans-serif;}
        /* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
        We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
    </style>
    <div  class="content-fluid bg-primary  p-5" id="mc_embed_signup">
        <form class="mx-auto" action="https://gmail.us21.list-manage.com/subscribe/post?u=9ca14176ce698bb3ec6889950&amp;id=40e940b2b7&amp;f_id=004babe1f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
            <h1 class="display-5 mb-4">Stay Updated!!!</h1>
            <div class="mx-auto" style="max-width: 600px;">
                <label style="color: black;" for="mce-EMAIL">Email Address</label>
                <input type="email" value="" class="form-control border-white p-2" name="EMAIL" class="required email" id="mce-EMAIL" required>
                <span id="mce-EMAIL-HELPERTEXT" class="helper_text"></span>
                <input type="submit" class="btn btn-dark px-4" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
            </div>
                <div id="mce-responses" class="clear foot">
                    <div class="response" id="mce-error-response" style="display:none"></div>
                    <div class="response"  style="color: black;" id="mce-success-response" style="display:none"></div>
                </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_9ca14176ce698bb3ec6889950_40e940b2b7" tabindex="-1" value=""></div>
                    <div class="optionalParent">
                        <div class="clear foot">
                            
                        </div>
                    </div>
                </div>
        </form>
    </div>
    <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
    <!--End mc_embed_signup-->


    <div class="container-fluid bg-dark text-secondary p-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white  mb-4">Quick Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-secondary mb-2" href="{% url 'index' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-secondary mb-2" href="{% url 'Eron_app:about' %}"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-secondary mb-2" href="{% url 'Eron_app:service' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                    <a class="text-secondary mb-2" href="{% url 'Eron_app:blog' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Blog Post</a>
                    <a class="text-secondary" href="{% url 'Eron_app:contact' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Popular Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-secondary mb-2" href="{% url 'index' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-secondary mb-2" href="{% url 'Eron_app:about' %}"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-secondary mb-2" href="{% url 'Eron_app:service' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                    <a class="text-secondary mb-2" href="{% url 'Eron_app:blog' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Blog Post</a>
                    <a class="text-secondary" href="{% url 'Eron_app:contact' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Get In Touch</h3>
                <p class="mb-2"><i class="fa fa-location-arrow" aria-hidden="true" style="color: #fff;"></i>Toronto, CANADA</p>
                <p class="mb-2"><i class="fa fa-envelope-open me-2" style="color: #fff;"></i> Eromonsalemconsulting@gmail.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt me-2" style="color: #fff;"></i>+1 647-562-8447</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Follow Us</h3>
                <div>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href="#"><i class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href="#"><i class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle" href="#"><i class="fab fa-instagram fw-normal"></i></a>
                </div>
            </div>
        </div>

    </div>
    <div class="container-fluid bg-dark text-secondary text-center border-top py-4 px-5" style="border-color: rgba(256, 256, 256, .1) !important;">
        <p class="m-0">&copy; <a class="text-secondary " style="text-decoration: none;" href="{% url 'index' %}">EROMON-SALEM 2023</a>
    </div>
    <!-- Footer End -->
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

  </body>
</html>

Eromonsalem/templates/FQA.html
<!doctype html>
{% extends "Base.html" %}
{% load static %}

  {% block body_block %}


            <!-- Page Header Start -->
            <div class="content-fluid bg-dark p-5">
                <div class="row">
                    <div class="col-12 text-center">
                        <h1 class="display-4 text-white">FAQs</h1>
                        <a href="{% url 'index' %}">Home</a>
                        <i class="far fa-square text-primary px-2"></i>
                        <a href="{% url 'Eron_app:FQA' %}">FAQs</a>
                    </div>
                </div>
            </div>
            <!-- Page Header End -->

             <!-- FQA Start -->
            <div class="container-fluid bg-secondary px-0" style="padding-bottom: 30px;">
                <div class="row g-0" style="padding-top: 30px;">
                    <div class="">
                        <h2 class="display-5 mb-4">Welcome to the Frequently Asked Questions (FAQ) page for Eromonsalemconsulting!</h2>
                        <p> Q: What services do we offer?<br>
                            A: Our company offers a range of IT consulting services, including but not limited to:<br>
                            
                            <strong>Technology strategy development,
                            IT infrastructure design and implementation,
                            Programming and Development,
                            Web Design,
                            Business process automation,
                            Custom software development,
                            Project management IT staff augmentation.</strong>
                        </p>
                        <p>
                            Q: How do you ensure the security of our company's data?<br>
                            A: We take the security of our clients' data very seriously.<br>
                            <strong>We use industry-leading security protocols and best practices to ensure that your data is protected at all times.
                            Additionally,we work closely with you to understand your specific security needs and develop a customized security strategy to address them.</strong>

                        </p>


                        <p>
                            Q: Can you work with our existing IT staff?<br>
                            A: Absolutely.<br> 
                            <strong>We can provide IT staff augmentation services to supplement your 
                            existing team or work collaboratively with them on projects.</strong>

                        </p>
                        <p>
                            Q: How much do your IT consulting services cost?<br>
                            A: The cost of our IT consulting services varies depending on the scope and complexity of the project.<br>
                            <strong>We provide custom quotes for each project after conducting a thorough assessment of your needs. 
                            However, we strive to provide competitive pricing while delivering high-quality services.</strong>
                            
                        </p>
                        <p>
                            Q: How do I know if I need Eromonsalemconsulting services?<br>
                            A: If you are experiencing any of the following issues, Our services may be beneficial for your business:<br>
                            
                            <strong>Inefficient technology infrastructure or outdated systems.
                            Security breaches or other cybersecurity concerns.
                            Difficulty implementing new technologies.
                            Limited IT staff or expertise.
                            Inability to keep up with industry trends.</strong>
                        </p>
                        <p>
                            Q: Do you offer ongoing support services?<br>
                            A: Yes, we offer ongoing support services to ensure that your technology infrastructure continues to meet your business needs.<br>
                            <strong>We provide various levels of support, ranging from on-call assistance to proactive monitoring and maintenance.</strong>
                        </p>
                        <p>
                            Q: How do I get started with your IT consulting services?<br>
                            A: The first step is to contact us to schedule a consultation.<br> 
                            <strong>During the consultation, we will discuss your specific needs and determine how our services can help your business. 
                            From there, we will provide a custom quote and develop a plan of action to begin the project.</strong>
                        </p>

                        
                    </div>
                </div>
            </div>
            <!-- FQAs End -->
    {% endblock %}

    


Eromonsalem/templates/about.html
<!doctype html>
{% extends "Base.html" %}
{% load static %}

  {% block body_block %}

    <!-- Page Header Start -->
    <div class="container-fluid bg-dark p-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-white">About Us</h1>
                <a href="{% url 'index'%}">Home</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="{% url 'Eron_app:about' %}">About</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- About Start -->
    <div class="container-fluid  p-0">
        <div class="row g-0">
            <div class="col-lg-6 py-6 px-5">
                <h1 class="display-5 mb-4 " style="padding-top: 30px;">Welcome To <span class="text-primary">Eromon-salem</span></h1>
                <h4 class="text-primary mb-4"> Our company offers a wide range of IT training services to help businesses and individuals develop the skills they need to succeed in today's digital landscape. Our training programs are designed to be flexible and adaptable, to meet the specific needs of our clients.</h4>
                <p class="mb-4">Whether you are driven by a need to modernize, gain a competitive advantage, or overcome a frustrating operational blocker, we are able to craft the best solution that will help your business grow. At Eromon-salem, we believe technology can connect people in powerful ways. This is why we give our utmost attention to each client to ensure all aspects of your objectives are accomplished.</p>
                <a href="{% url 'Eron_app:service' %}" class="btn btn-primary py-md-3 px-md-5 rounded-pill">Get A Quote</a>
            </div>
            <div class="col-lg-6">
                <div class="h-100 d-flex flex-column justify-content-center bg-primary p-5">
                    <div class="d-flex text-white mb-5">
                        <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                            <i class="fa fa-signal fa-2x" aria-hidden="true"></i>
                        </div>
                        <div class="ps-4">
                            <h3>IT Services</h3>
                            <p class="mb-0">Complete technology solutions for all size businesses,get in contact and let us know about your needs</p>
                        </div>
                    </div>
                    <div class="d-flex text-white mb-5">
                        <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                            <i class="fa fa-chart-line fs-4"></i>
                        </div>
                        <div class="ps-4">
                            <h3>IT Project management</h3>
                            <p class="mb-0">We offer training on IT project management methodologies such as Agile, Scrum, Waterfall and more, to help teams deliver projects on-time, on-budget, and to the satisfaction of stakeholders.</p>
                        </div>
                    </div>
                    <div class="d-flex text-white">
                        <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                            <i class="fa fa-database fa-2x" aria-hidden="true"></i>
                        </div>
                        <div class="ps-4">
                            <h3>Data Science</h3>
                            <p class="mb-0">Our data science  programs cover the latest techniques and technologies for data analysis, Excel spreadsheet and are designed to help businesses stay competitive in today's data-driven world.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->


    <!-- Team Start -->
    <div class="content-fluid py-6 px-5">
        <div class="text-center mx-auto mb-5" style="max-width: 600px;">
            <h1 class="display-5 mb-0">Management Team</h1>
            <hr class="w-25 mx-auto bg-primary">
        </div>
        <div class="row g-5">
            <div class="col-lg-4">
                <div class="team-item position-relative overflow-hidden">
                    <img class="img-fluid w-100" src="{% static "images/Team03.png" %}" alt="einst">
                    <div class="team-text w-100 position-absolute top-50 text-center bg-primary p-4">
                        <h3 class="text-white">EINSTEIN AIKHUELE</h3>
                        <p class="text-white text-uppercase mb-0">FULL STACK DEVELOPER / DATABASE ADMIN</p>
                    </div>
                </div>
                <div style="padding-top: 10px;">
                    <a href="https://www.linkedin.com/in/einstein-aikhuele" class="btn btn-primary py-md-3 px-md-3 button"> Learn More</a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-item position-relative overflow-hidden">
                    <img class="img-fluid w-100" src="{% static "images/team2.JPG" %}"  alt="newt">
                    <div class="team-text w-100 position-absolute top-50 text-center bg-primary p-4">
                        <h3 class="text-white">NEWTON AIKHUELE </h3>
                        <p class="text-white text-uppercase mb-0">GRAPHIC DESIGNER / H.R</p>
                    </div>
                </div>
                <div style="padding-top: 20px;">
                    <a href="https://www.linkedin.com/in/aikhuele-newton-a094bb17b?trk=contact-info" class="btn btn-primary py-md-3 px-md-3 button"> Learn More</a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-item position-relative overflow-hidden">
                    <img class="img-fluid w-100" src="{% static "images/TEAM-005.jpg" %}"  alt="theo">
                    <div class="team-text w-100 position-absolute top-50 text-center bg-primary p-4">
                        <h3 class="text-white">THEOPHILUS AIKHUELE</h3>
                        <p class="text-white text-uppercase mb-0">MANAGEMENT CONSULTANT</p>
                    </div>
                </div>
                <div style="padding-top: 20px;">
                    <a href="http://www.linkedin.com/in/theophilus-aikhuele" class="btn btn-primary py-md-3 px-md-3 button"> Learn More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Team End -->
   {% endblock %}

Eromonsalem/templates/contact.html
<!doctype html>
{% extends "Base.html" %}
{% load static %}

  {% block body_block %}

    <!-- Page Header Start -->
    <div class="content-fluid bg-dark p-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-white">Contact Us</h1>
                <a href="{% url 'index' %}">Home</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="{% url 'Eron_app:contact' %}">Contact</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="container-fluid bg-secondary px-0" style="padding-bottom: 30px;">
        <div class="row g-0" style="padding-top: 30px;">
            <div class="col-lg-6 py-6 px-5">
                <h1 class="display-5 mb-4">Contact For Any Queries</h1>
                <form  method="POST">
                    <div class="row g-3">
                        {{ form.as_p }}
                         {% csrf_token %}
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3" type="submit " value="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-6" style="min-height: 400px;">
                <div class="position-relative h-100">
                 <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6949743.029139142!2d-89.70677649332225!3d49.44574780879038!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cce05b25f5113af%3A0x70f8425629621e09!2sOntario%2C%20Canada!5e0!3m2!1sen!2sng!4v1676030643057!5m2!1sen!2sng" 
                 width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
   {% endblock %}

Eromonsalem/templates/thanks.html
<!doctype html>
{% extends "Base.html" %}
{% load static %}

  {% block body_block %}

  <div class="text-center content-fluid" style="padding-bottom: 30px;">
    <h1>Thank You !</h1>
    <h2> We will get in touch with you soon </h2>
    <a href="{% url 'index' %}"  class="btn btn-primary " >Back Home</a>
  </div>

  {% endblock %}